root: true
extends:
  - react-app
  - react-app/jest
  - plugin:import/errors

rules: {}

settings:
  import/ignore:
    - node_modules
    - "*.coffee$"

  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx

